### ISSUE TITLE
Permission denied on version 0.70 of the client

### ISSUE THREAD

**Issue by RichardPBerry** [mytardis/mydata#121] opened 2017-12-01 04:15 UTC
Uploading multiple files via SSH on version 0.7 of client results permission denied error. Files start to upload but fail at seemingly random point.

![screen shot 2017-12-01 at 3 09 53 pm](https://user-images.githubusercontent.com/22140635/33467681-5999e300-d6aa-11e7-8a97-06537cc773ff.png)

 The error is:
`scp: /research/mytardis/receiving/Richard_test-ssh9-50/0801/0800/SPECTRO/1AVE: Permission denied`

Checking the permissions on the receiving share shows that the directory the client is trying to upload to has the following permissions:

drw-rwS---. 3 mydatauser mydatagrp          3 Dec  1 14:35 SPECTRO

**Comment by wettenhj** [comment] 2017-12-01 06:00
Thanks for reporting this, @RichardPBerry 

I have come across this problem before and I was hoping that it was fixed in v0.7.0, but clearly it isn't fixed reliably (unless the SPECTRO directory on your SCP server was created by a previous MyData version).  The intended mode of directories created by MyData, in /research/mytardis/receiving/ is 2770, so as a temporary workaround you can fix the permissions on the SCP server by doing something like this: ```find . -type d -exec chmod 2770 {} \;``` and if any files have the wrong permissions, you can fix them too with ```find . -type f -exec chmod 660 {} \;```

We used to recommend using umask on the SCP server to ensure that files and directories were created with the correct permissions, but we found that to be unreliable, so now MyData explicitly sets permissions after creating remote files or directories.  If the SPECTRO directory was definitely created with the latest MyData (v0.7.0), then it would be great if you could reproduce MyData creating a directory with incorrect permissions while running with debug logging - tick the debug checkbox in MyData's Log view) and then share the relevant bits of the debug log (privately is fine if preferred).

**Comment by wettenhj** [comment] 2017-12-12 22:10
I've been able to reproduce this, but not in a 100% deterministic manner, so I think there are race conditions when multiple threads both find that a remote directory needs to be created to upload a local file into and they both try to create the remote directory at the same time.  This can be prevented easily with thread synchronization, so we'll do that in the next MyData build (v0.7.1-beta1), but we should also consider the root cause of the permissions problem, which could be related to the scp.exe binary bundled with v0.7.0 from OpenSSH 7.3p1.  We'll do some testing and check whether changing scp versions improves the situation.

**Comment by wettenhj** [comment] 2017-12-13 00:41
Actually I've reproduced this while running MyData on Linux, so it doesn't appear to be an issue with the ssh.exe / scp.exe version bundled with MyData's Windows build.

**Comment by wettenhj** [comment] 2017-12-17 04:49
As this issue appears to be caused by race conditions, it's difficult to provide an iron-clad guarantee that it's been fixed, but it should be fixed by this commit: https://github.com/mytardis/mydata/commit/224575aadb48471e58a052e7b292d5a3e6142a2e included in the v0.7.1-beta1 builds here: https://github.com/mytardis/mydata/releases/tag/v0.7.1-beta1

Unfortunately I don't have a code-signing certificate for signing Windows beta builds - I can get them signed but I need to submit a request for that.  If you want to use an unsigned build, feel free to request an MD5 or SHA sum so you can manually verify it.

**Comment by wettenhj** [comment] 2018-01-03 03:38
This bug still exists in v0.7.1-beta1, but I'm pretty confident that it's been fixed once and for all in the latest commits pushed to the develop branch.  I'd like to do a bit more local testing, then I'll release a new version.

**Comment by RichardPBerry** [comment] 2018-01-08 03:44
Many thanks for the update and for looking at this @wettenhj. I'm more than happy to do some testing when you've been able to release the next beta for download.

**Comment by wettenhj** [comment] 2018-01-09 00:41
@RichardPBerry, a new beta build is available here: https://github.com/mytardis/mydata/releases/tag/v0.7.1-beta2

Testing / feedback would be most welcome!

**Comment by wettenhj** [comment] 2018-09-07 02:03
Resolved in v0.7.1

**Closed by wettenhj** 2018-09-07 02:03 UTC
Labels: bug, confirmed
